#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

if [[ -f .env ]]; then
  echo ".env already exists; leaving it unchanged."
  echo "Run: docker compose up -d --build"
  exit 0
fi

command -v openssl >/dev/null 2>&1 || {
  echo "ERROR: openssl is required to generate installation secrets." >&2
  exit 1
}

POSTGRES_PASSWORD="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 64)"
SEED_ADMIN_PASSWORD="$(openssl rand -hex 20)"

cat > .env <<EOF
# Generated by setup-env.sh for this installation.
# Keep this file private and never commit it to source control.
POSTGRES_USER=easynet
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=easynet

JWT_SECRET=${JWT_SECRET}
PORT=4000
CLIENT_ORIGIN=http://localhost:8080
NODE_ENV=production
WEB_PORT=8080

SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
SEED_DEMO_DATA=false

SMS_PROVIDER_URL=
SMS_PROVIDER_TOKEN=
TELEBIRR_API_URL=
TELEBIRR_WEBHOOK_SECRET=
CBE_BIRR_API_URL=
CBE_BIRR_WEBHOOK_SECRET=
QR_RENDER_URL=
EOF

chmod 600 .env

echo
echo "EasyNet HIS environment created: .env"
echo "Admin login after seeding:"
echo "  Email:    admin@easynet.local"
echo "  Password: ${SEED_ADMIN_PASSWORD}"
echo
echo "Start the stack with:"
echo "  docker compose up -d --build"
echo "Then seed with:"
echo "  docker compose exec api npm run db:seed"
echo
echo "For production, replace generated secrets with your deployment secret manager values."
