CREATE TABLE "OpdQueueEntry" ("id" TEXT NOT NULL,"queueNumber" TEXT NOT NULL,"patientId" TEXT NOT NULL,"departmentId" TEXT NOT NULL,"providerId" TEXT,"appointmentId" TEXT,"encounterId" TEXT,"priority" TEXT NOT NULL DEFAULT 'NORMAL',"status" TEXT NOT NULL DEFAULT 'WAITING',"checkInAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"calledAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"notes" TEXT,CONSTRAINT "OpdQueueEntry_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "OpdQueueEntry_queueNumber_key" ON "OpdQueueEntry"("queueNumber");
CREATE UNIQUE INDEX "OpdQueueEntry_encounterId_key" ON "OpdQueueEntry"("encounterId");
CREATE INDEX "OpdQueueEntry_departmentId_status_checkInAt_idx" ON "OpdQueueEntry"("departmentId","status","checkInAt");
CREATE INDEX "OpdQueueEntry_patientId_checkInAt_idx" ON "OpdQueueEntry"("patientId","checkInAt");
ALTER TABLE "OpdQueueEntry" ADD CONSTRAINT "OpdQueueEntry_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OpdQueueEntry" ADD CONSTRAINT "OpdQueueEntry_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OpdQueueEntry" ADD CONSTRAINT "OpdQueueEntry_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OpdQueueEntry" ADD CONSTRAINT "OpdQueueEntry_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OpdQueueEntry" ADD CONSTRAINT "OpdQueueEntry_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "WardTransfer" ("id" TEXT NOT NULL,"admissionId" TEXT NOT NULL,"fromWardId" TEXT,"fromBedId" TEXT,"toWardId" TEXT NOT NULL,"toBedId" TEXT NOT NULL,"reason" TEXT,"status" TEXT NOT NULL DEFAULT 'COMPLETED',"transferredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WardTransfer_pkey" PRIMARY KEY ("id"));
CREATE INDEX "WardTransfer_admissionId_transferredAt_idx" ON "WardTransfer"("admissionId","transferredAt");
ALTER TABLE "WardTransfer" ADD CONSTRAINT "WardTransfer_admissionId_fkey" FOREIGN KEY ("admissionId") REFERENCES "Admission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WardTransfer" ADD CONSTRAINT "WardTransfer_fromWardId_fkey" FOREIGN KEY ("fromWardId") REFERENCES "Ward"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WardTransfer" ADD CONSTRAINT "WardTransfer_toWardId_fkey" FOREIGN KEY ("toWardId") REFERENCES "Ward"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WardTransfer" ADD CONSTRAINT "WardTransfer_fromBedId_fkey" FOREIGN KEY ("fromBedId") REFERENCES "Bed"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WardTransfer" ADD CONSTRAINT "WardTransfer_toBedId_fkey" FOREIGN KEY ("toBedId") REFERENCES "Bed"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "NursingTask" ("id" TEXT NOT NULL,"admissionId" TEXT,"patientId" TEXT NOT NULL,"assignedToId" TEXT,"taskType" TEXT NOT NULL,"priority" TEXT NOT NULL DEFAULT 'NORMAL',"status" TEXT NOT NULL DEFAULT 'OPEN',"dueAt" TIMESTAMP(3),"notes" TEXT,"completedAt" TIMESTAMP(3),CONSTRAINT "NursingTask_pkey" PRIMARY KEY ("id"));
CREATE INDEX "NursingTask_patientId_status_dueAt_idx" ON "NursingTask"("patientId","status","dueAt");
CREATE INDEX "NursingTask_assignedToId_status_idx" ON "NursingTask"("assignedToId","status");
ALTER TABLE "NursingTask" ADD CONSTRAINT "NursingTask_admissionId_fkey" FOREIGN KEY ("admissionId") REFERENCES "Admission"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NursingTask" ADD CONSTRAINT "NursingTask_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "NursingTask" ADD CONSTRAINT "NursingTask_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
